package com.shiyi.meng.meng;


import com.shiyi.meng.model.base.BaseAbnormalstore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Abnormalstore extends BaseAbnormalstore<Abnormalstore> {
	public static final Abnormalstore dao = new Abnormalstore().dao();
}
