package com.shiyi.meng.meng;


import com.shiyi.meng.model.base.BaseBill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bill extends BaseBill<Bill> {
	public static final Bill dao = new Bill().dao();
}
