package com.shiyi.meng.meng;

import com.shiyi.meng.model.base.BaseDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Device extends BaseDevice<Device> {
	public static final Device dao = new Device().dao();
}
