package com.shiyi.meng.meng;


import com.shiyi.meng.model.base.BaseHint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hint extends BaseHint<Hint> {
	public static final Hint dao = new Hint().dao();
}
