package com.shiyi.meng.meng;

import com.shiyi.meng.model.base.BaseSearchrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Searchrecord extends BaseSearchrecord<Searchrecord> {
	public static final Searchrecord dao = new Searchrecord().dao();
}
