package com.shiyi.meng.meng;

import com.shiyi.meng.model.base.BaseStore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Store extends BaseStore<Store> {
	public static final Store dao = new Store().dao();
}
