package com.shiyi.meng.meng;

import com.shiyi.meng.model.base.BaseUsercontract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Usercontract extends BaseUsercontract<Usercontract> {
	public static final Usercontract dao = new Usercontract().dao();
}
