package com.shiyi.meng.meng;

import com.shiyi.meng.model.base.BaseVoucher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Voucher extends BaseVoucher<Voucher> {
	public static final Voucher dao = new Voucher().dao();
}
