server:
  port: 8080
  ssl:
    key-store: 2570754_moxicanyin.cn.pfx
    key-store-password: QpX7p149
    key-store-type: PKCS12

jfinal:
  debug: true
  jdbcUrl: jdbc:mysql://47.110.248.49:3306/catering?characterEncoding=utf8&serverTimezone=Asia/Shanghai&initialSize=90&maxActive=130&wait_timeout=288000
  dbUser: root
  dbPwd: 123456
