package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHint<M extends BaseHint<M>> extends Model<M> implements IBean {

	public void setHId(java.math.BigInteger hId) {
		set("hId", hId);
	}

	public java.math.BigInteger getHId() {
		return get("hId");
	}

	public void setHLoc(String hLoc) {
		set("hLoc", hLoc);
	}

	public String getHLoc() {
		return get("hLoc");
	}

	public void setHContent(String hContent) {
		set("hContent", hContent);
	}

	public String getHContent() {
		return get("hContent");
	}

	public void setHCreateTime(java.util.Date hCreateTime) {
		set("hCreateTime", hCreateTime);
	}

	public java.util.Date getHCreateTime() {
		return get("hCreateTime");
	}

	public void setHModifyTime(java.util.Date hModifyTime) {
		set("hModifyTime", hModifyTime);
	}

	public java.util.Date getHModifyTime() {
		return get("hModifyTime");
	}

}
