package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFollowdevice<M extends BaseFollowdevice<M>> extends Model<M> implements IBean {

	public void setFdId(java.math.BigInteger fdId) {
		set("fdId", fdId);
	}

	public java.math.BigInteger getFdId() {
		return get("fdId");
	}

	public void setFdDevice(java.math.BigInteger fdDevice) {
		set("fdDevice", fdDevice);
	}

	public java.math.BigInteger getFdDevice() {
		return get("fdDevice");
	}

	public void setFdUser(java.math.BigInteger fdUser) {
		set("fdUser", fdUser);
	}

	public java.math.BigInteger getFdUser() {
		return get("fdUser");
	}

	public void setFdCreateTime(java.util.Date fdCreateTime) {
		set("fdCreateTime", fdCreateTime);
	}

	public java.util.Date getFdCreateTime() {
		return get("fdCreateTime");
	}

	public void setFdModifyTime(java.util.Date fdModifyTime) {
		set("fdModifyTime", fdModifyTime);
	}

	public java.util.Date getFdModifyTime() {
		return get("fdModifyTime");
	}

}
