package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDevicebusiness<M extends BaseDevicebusiness<M>> extends Model<M> implements IBean {

	public void setDbId(java.math.BigInteger dbId) {
		set("dbId", dbId);
	}

	public java.math.BigInteger getDbId() {
		return get("dbId");
	}

	public void setDbUser(java.math.BigInteger dbUser) {
		set("dbUser", dbUser);
	}

	public java.math.BigInteger getDbUser() {
		return get("dbUser");
	}

	public void setDbType(Integer dbType) {
		set("dbType", dbType);
	}

	public Integer getDbType() {
		return get("dbType");
	}

	public void setDbLoc(String dbLoc) {
		set("dbLoc", dbLoc);
	}

	public String getDbLoc() {
		return get("dbLoc");
	}

	public void setDbLng(Integer dbLng) {
		set("dbLng", dbLng);
	}

	public Integer getDbLng() {
		return get("dbLng");
	}

	public void setDbLat(Integer dbLat) {
		set("dbLat", dbLat);
	}

	public Integer getDbLat() {
		return get("dbLat");
	}

	public void setDbName(String dbName) {
		set("dbName", dbName);
	}

	public String getDbName() {
		return get("dbName");
	}

	public void setDbPhone(String dbPhone) {
		set("dbPhone", dbPhone);
	}

	public String getDbPhone() {
		return get("dbPhone");
	}

	public void setDbDeviceType(java.math.BigInteger dbDeviceType) {
		set("dbDeviceType", dbDeviceType);
	}

	public java.math.BigInteger getDbDeviceType() {
		return get("dbDeviceType");
	}

	public void setDbExplain(String dbExplain) {
		set("dbExplain", dbExplain);
	}

	public String getDbExplain() {
		return get("dbExplain");
	}

	public void setDbStatus(Integer dbStatus) {
		set("dbStatus", dbStatus);
	}

	public Integer getDbStatus() {
		return get("dbStatus");
	}

	public void setDbFailReason(String dbFailReason) {
		set("dbFailReason", dbFailReason);
	}

	public String getDbFailReason() {
		return get("dbFailReason");
	}

	public void setDbCreateTime(java.util.Date dbCreateTime) {
		set("dbCreateTime", dbCreateTime);
	}

	public java.util.Date getDbCreateTime() {
		return get("dbCreateTime");
	}

	public void setDbModifyTime(java.util.Date dbModifyTime) {
		set("dbModifyTime", dbModifyTime);
	}

	public java.util.Date getDbModifyTime() {
		return get("dbModifyTime");
	}

}
