package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStore<M extends BaseStore<M>> extends Model<M> implements IBean {

	public void setSId(java.math.BigInteger sId) {
		set("sId", sId);
	}

	public java.math.BigInteger getSId() {
		return get("sId");
	}

	public void setSUId(java.math.BigInteger sUId) {
		set("sUId", sUId);
	}

	public java.math.BigInteger getSUId() {
		return get("sUId");
	}

	public void setSColumn(Integer sColumn) {
		set("sColumn", sColumn);
	}

	public Integer getSColumn() {
		return get("sColumn");
	}

	public void setSPhoto(String sPhoto) {
		set("sPhoto", sPhoto);
	}

	public String getSPhoto() {
		return get("sPhoto");
	}

	public void setSName(String sName) {
		set("sName", sName);
	}

	public String getSName() {
		return get("sName");
	}

	public void setSDes(String sDes) {
		set("sDes", sDes);
	}

	public String getSDes() {
		return get("sDes");
	}

	public void setSLoc(String sLoc) {
		set("sLoc", sLoc);
	}

	public String getSLoc() {
		return get("sLoc");
	}

	public void setSLng(String sLng) {
		set("sLng", sLng);
	}

	public String getSLng() {
		return get("sLng");
	}

	public void setSLat(String sLat) {
		set("sLat", sLat);
	}

	public String getSLat() {
		return get("sLat");
	}

    public void setSCity(String sCity) {
        set("sCity", sCity);
    }

    public String getSCity() {
        return get("sCity");
    }

	public void setSUserWriteLoc(String sUserWriteLoc) {
		set("sUserWriteLoc", sUserWriteLoc);
	}

	public String getSUserWriteLoc() {
		return get("sUserWriteLoc");
	}

	public void setSType(Integer sType) {
		set("sType", sType);
	}

	public Integer getSType() {
		return get("sType");
	}

	public void setSAera(Float sAera) {
		set("sAera", sAera);
	}

	public Float getSAera() {
		return get("sAera");
	}

	public void setSRentMoney(Float sRentMoney) {
		set("sRentMoney", sRentMoney);
	}

	public Float getSRentMoney() {
		return get("sRentMoney");
	}

	public void setSTranMoney(Float sTranMoney) {
		set("sTranMoney", sTranMoney);
	}

	public Float getSTranMoney() {
		return get("sTranMoney");
	}

	public void setSPayMethod(String sPayMethod) {
		set("sPayMethod", sPayMethod);
	}

	public String getSPayMethod() {
		return get("sPayMethod");
	}

	public void setSTotalFloor(Integer sTotalFloor) {
		set("sTotalFloor", sTotalFloor);
	}

	public Integer getSTotalFloor() {
		return get("sTotalFloor");
	}

	public void setSStoreStatus(Integer sStoreStatus) {
		set("sStoreStatus", sStoreStatus);
	}

	public Integer getSStoreStatus() {
		return get("sStoreStatus");
	}

	public void setSLeftTime(String sLeftTime) {
		set("sLeftTime", sLeftTime);
	}

	public String getSLeftTime() {
		return get("sLeftTime");
	}

	public void setSPhone(String sPhone) {
		set("sPhone", sPhone);
	}

	public String getSPhone() {
		return get("sPhone");
	}

    public void setSConnectType(Integer sConnectType) {
        set("sConnectType", sConnectType);
    }

    public Integer getSConnectType() {
        return get("sConnectType");
    }

    public void setSConnectWay(String sConnectWay) {
        set("sConnectWay", sConnectWay);
    }

    public String getSConnectWay() {
        return get("sConnectWay");
    }

	public void setSConName(String sConName) {
		set("sConName", sConName);
	}

	public String getSConName() {
		return get("sConName");
	}

	public void setSClick(String sClick) {
		set("sClick", sClick);
	}

	public String getSClick() {
		return get("sClick");
	}

	public void setSTag(String sTag) {
		set("sTag", sTag);
	}

	public String getSTag() {
		return get("sTag");
	}

	public void setSLicense(String sLicense) {
		set("sLicense", sLicense);
	}

	public String getSLicense() {
		return get("sLicense");
	}

	public void setSIdCard(String sIdCard) {
		set("sIdCard", sIdCard);
	}

	public String getSIdCard() {
		return get("sIdCard");
	}

	public void setSECharge(Float sECharge) {
		set("sECharge", sECharge);
	}

	public Float getSECharge() {
		return get("sECharge");
	}

	public void setSWCharge(Float sWCharge) {
		set("sWCharge", sWCharge);
	}

	public Float getSWCharge() {
		return get("sWCharge");
	}

	public void setSFee(Float sFee) {
		set("sFee", sFee);
	}

	public Float getSFee() {
		return get("sFee");
	}

	public void setSHasPark(Integer sHasPark) {
		set("sHasPark", sHasPark);
	}

	public Integer getSHasPark() {
		return get("sHasPark");
	}

	public void setSComment(String sComment) {
		set("sComment", sComment);
	}

	public String getSComment() {
		return get("sComment");
	}

	public void setSWareHouse(Integer sWareHouse) {
		set("sWareHouse", sWareHouse);
	}

	public Integer getSWareHouse() {
		return get("sWareHouse");
	}

	public void setSStatus(Integer sStatus) {
		set("sStatus", sStatus);
	}

	public Integer getSStatus() {
		return get("sStatus");
	}

	public void setSDeposit(Float sDeposit) {
		set("sDeposit", sDeposit);
	}

	public Float getSDeposit() {
		return get("sDeposit");
	}

	public void setSPriceType(Integer sPriceType) {
		set("sPriceType", sPriceType);
	}

	public Integer getSsPriceType() {
		return get("sPriceType");
	}

	public void setSRefuseReason(String sRefuseReason) {
		set("sRefuseReason", sRefuseReason);
	}

	public String getSRefuseReason() {
		return get("sRefuseReason");
	}

    public void setSFlushTime(BigInteger sFlushTime) {
        set("sFlushTime", sFlushTime);
    }

    public BigInteger getSFlushTime() {
        return get("sFlushTime");
    }

    public void setSSchool(BigInteger sSchool) {
        set("sSchool", sSchool);
    }

    public BigInteger getSSchool() {
        return get("sSchool");
    }

    public void setSBusiness(BigInteger sBusiness) {
        set("sBusiness", sBusiness);
    }

    public BigInteger getSBusiness() {
        return get("sBusiness");
    }

    public void setSSpot(BigInteger sSpot) {
        set("sSpot", sSpot);
    }

    public BigInteger getSSpot() {
        return get("sSpot");
    }

	public void setSCreateTime(java.util.Date sCreateTime) {
		set("sCreateTime", sCreateTime);
	}

	public java.util.Date getSCreateTime() {
		return get("sCreateTime");
	}

	public void setSModifyTime(java.util.Date sModifyTime) {
		set("sModifyTime", sModifyTime);
	}

	public java.util.Date getSModifyTime() {
		return get("sModifyTime");
	}

    public String  getSstartTime(){return get("sStartTime");};

	public void setsStartTime(String sStartTime){set("sStartTime",sStartTime);}

	public String  getSFreeTime(){return get("sFreeTime");};

	public void setsFreeTime(String sFreeTime){set("sFreeTime",sFreeTime);}

}
