package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFollowstore<M extends BaseFollowstore<M>> extends Model<M> implements IBean {

	public void setFsId(java.math.BigInteger fsId) {
		set("fsId", fsId);
	}

	public java.math.BigInteger getFsId() {
		return get("fsId");
	}

	public void setFsStore(java.math.BigInteger fsStore) {
		set("fsStore", fsStore);
	}

	public java.math.BigInteger getFsStore() {
		return get("fsStore");
	}

	public void setFsUser(java.math.BigInteger fsUser) {
		set("fsUser", fsUser);
	}

	public java.math.BigInteger getFsUser() {
		return get("fsUser");
	}

	public void setFsStatus(Integer fsStatus) {
		set("fsStatus", fsStatus);
	}

	public Integer getFsStatus() {
		return get("fsStatus");
	}

	public void setFsCreateTime(java.util.Date fsCreateTime) {
		set("fsCreateTime", fsCreateTime);
	}

	public java.util.Date getFsCreateTime() {
		return get("fsCreateTime");
	}

	public void setFsModifyTime(java.util.Date fsModifyTime) {
		set("fsModifyTime", fsModifyTime);
	}

	public java.util.Date getFsModifyTime() {
		return get("fsModifyTime");
	}

}
