package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;
import org.springframework.context.annotation.Bean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public void setAId(java.math.BigInteger aId) {
		set("aId", aId);
	}

	public java.math.BigInteger getAId() {
		return get("aId");
	}

	public void setAAcount(String aAcount) {
		set("aAcount", aAcount);
	}

	public String getAAcount() {
		return get("aAcount");
	}

	public void setAPwd(String aPwd) {
		set("aPwd", aPwd);
	}

	public String getAPwd() {
		return get("aPwd");
	}

	public void setACreateTime(java.util.Date aCreateTime) {
		set("aCreateTime", aCreateTime);
	}

	public java.util.Date getACreateTime() {
		return get("aCreateTime");
	}

	public void setAModifyTime(java.util.Date aModifyTime) {
		set("aModifyTime", aModifyTime);
	}

	public java.util.Date getAModifyTime() {
		return get("aModifyTime");
	}

}
