package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlatbill<M extends BasePlatbill<M>> extends Model<M> implements IBean {

	public void setPbId(java.math.BigInteger pbId) {
		set("pbId", pbId);
	}

	public java.math.BigInteger getPbId() {
		return get("pbId");
	}

	public void setPbType(java.math.BigInteger pbType) {
		set("pbType", pbType);
	}

	public java.math.BigInteger getPbType() {
		return get("pbType");
	}

	public void setPbUser(java.math.BigInteger pbUser) {
		set("pbUser", pbUser);
	}

	public java.math.BigInteger getPbUser() {
		return get("pbUser");
	}

	public void setPbMoney(Float pbMoney) {
		set("pbMoney", pbMoney);
	}

	public Float getPbMoney() {
		return get("pbMoney");
	}

	public void setPbCreateTime(java.util.Date pbCreateTime) {
		set("pbCreateTime", pbCreateTime);
	}

	public java.util.Date getPbCreateTime() {
		return get("pbCreateTime");
	}

	public void setPbModifyTime(java.util.Date pbModifyTime) {
		set("pbModifyTime", pbModifyTime);
	}

	public java.util.Date getPbModifyTime() {
		return get("pbModifyTime");
	}

}
