package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStoreloc<M extends BaseStoreloc<M>> extends Model<M> implements IBean {

	public void setSlId(java.math.BigInteger slId) {
		set("slId", slId);
	}

	public java.math.BigInteger getSlId() {
		return get("slId");
	}

	public void setSlStore(java.math.BigInteger slStore) {
		set("slStore", slStore);
	}

	public java.math.BigInteger getSlStore() {
		return get("slStore");
	}

	public void setSlType(Integer slType) {
		set("slType", slType);
	}

	public Integer getSlType() {
		return get("slType");
	}

	public void setSlName(String slName) {
		set("slName", slName);
	}

	public String getSlName() {
		return get("slName");
	}

	public void setSlDistance(String slDistance) {
		set("slDistance", slDistance);
	}

	public String getSlDistance() {
		return get("slDistance");
	}

	public void setSlCreateTime(java.util.Date slCreateTime) {
		set("slCreateTime", slCreateTime);
	}

	public java.util.Date getSlCreateTime() {
		return get("slCreateTime");
	}

	public void setSlModifyTime(java.util.Date slModifyTime) {
		set("slModifyTime", slModifyTime);
	}

	public java.util.Date getSlModifyTime() {
		return get("slModifyTime");
	}

}
