package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVoucher<M extends BaseVoucher<M>> extends Model<M> implements IBean {

	public void setVId(java.math.BigInteger vId) {
		set("vId", vId);
	}

	public java.math.BigInteger getVId() {
		return get("vId");
	}

	public void setVName(String vName) {
		set("vName", vName);
	}

	public String getVName() {
		return get("vName");
	}

	public void setVFunction(String vFunction) {
		set("vFunction", vFunction);
	}

	public String getVFunction() {
		return get("vFunction");
	}

	public void setVMoney(Float vMoney) {
		set("vMoney", vMoney);
	}

	public Float getVMoney() {
		return get("vMoney");
	}

	public void setVCreateTime(java.util.Date vCreateTime) {
		set("vCreateTime", vCreateTime);
	}

	public java.util.Date getVCreateTime() {
		return get("vCreateTime");
	}

	public void setVModifyTime(java.util.Date vModifyTime) {
		set("vModifyTime", vModifyTime);
	}

	public java.util.Date getVModifyTime() {
		return get("vModifyTime");
	}

}
