package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCityloc<M extends BaseCityloc<M>> extends Model<M> implements IBean {

	public void setClId(java.math.BigInteger clId) {
		set("clId", clId);
	}

	public java.math.BigInteger getClId() {
		return get("clId");
	}

	public void setClCity(String clCity) {
		set("clCity", clCity);
	}

	public String getClCity() {
		return get("clCity");
	}

	public void setClType(Integer clType) {
		set("clType", clType);
	}

	public Integer getClType() {
		return get("clType");
	}

	public void setClName(String clName) {
		set("clName", clName);
	}

	public String getClName() {
		return get("clName");
	}

	public void setClLng(Float clLng) {
		set("clLng", clLng);
	}

	public Float getClLng() {
		return get("clLng");
	}

	public void setClLat(Float clLat) {
		set("clLat", clLat);
	}

	public Float getClLat() {
		return get("clLat");
	}

	public void setClCreateTime(java.util.Date clCreateTime) {
		set("clCreateTime", clCreateTime);
	}

	public java.util.Date getClCreateTime() {
		return get("clCreateTime");
	}

	public void setClModifyTime(java.util.Date ClModifyTime) {
		set("ClModifyTime", ClModifyTime);
	}

	public java.util.Date getClModifyTime() {
		return get("ClModifyTime");
	}

}
