package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTransfermoney<M extends BaseTransfermoney<M>> extends Model<M> implements IBean {

	public void setTmId(java.math.BigInteger tmId) {
		set("tmId", tmId);
	}

	public java.math.BigInteger getTmId() {
		return get("tmId");
	}

	public void setTmFrom(java.math.BigInteger tmFrom) {
		set("tmFrom", tmFrom);
	}

	public java.math.BigInteger getTmFrom() {
		return get("tmFrom");
	}

	public void setTmTo(java.math.BigInteger tmTo) {
		set("tmTo", tmTo);
	}

	public java.math.BigInteger getTmTo() {
		return get("tmTo");
	}

	public void setTmMoney(Float tmMoney) {
		set("tmMoney", tmMoney);
	}

	public Float getTmMoney() {
		return get("tmMoney");
	}

	public void setTmCreateTime(java.util.Date tmCreateTime) {
		set("tmCreateTime", tmCreateTime);
	}

	public java.util.Date getTmCreateTime() {
		return get("tmCreateTime");
	}

	public void setTmModifyTime(java.util.Date tmModifyTime) {
		set("tmModifyTime", tmModifyTime);
	}

	public java.util.Date getTmModifyTime() {
		return get("tmModifyTime");
	}

}
