package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBill<M extends BaseBill<M>> extends Model<M> implements IBean {

	public void setBId(java.math.BigInteger bId) {
		set("bId", bId);
	}

	public java.math.BigInteger getBId() {
		return get("bId");
	}

	public void setBDevice(java.math.BigInteger bDevice) {
		set("bDevice", bDevice);
	}

	public java.math.BigInteger getBDevice() {
		return get("bDevice");
	}

	public void setBSaler(java.math.BigInteger bSaler) {
		set("bSaler", bSaler);
	}

	public java.math.BigInteger getBSaler() {
		return get("bSaler");
	}

	public void setBBuyer(Long bBuyer) {
		set("bBuyer", bBuyer);
	}

	public Long getBBuyer() {
		return get("bBuyer");
	}

	public void setBCreateTime(java.util.Date bCreateTime) {
		set("bCreateTime", bCreateTime);
	}

	public java.util.Date getBCreateTime() {
		return get("bCreateTime");
	}

	public void setBModifyTime(java.util.Date bModifyTime) {
		set("bModifyTime", bModifyTime);
	}

	public java.util.Date getBModifyTime() {
		return get("bModifyTime");
	}

}
