package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdvert<M extends BaseAdvert<M>> extends Model<M> implements IBean {

	public void setAId(java.math.BigInteger aId) {
		set("aId", aId);
	}

	public java.math.BigInteger getAId() {
		return get("aId");
	}

	public void setAName(String aName) {
		set("aName", aName);
	}

	public String getAName() {
		return get("aName");
	}

	public void setAContent(String aContent) {
		set("aContent", aContent);
	}

	public String getAContent() {
		return get("aContent");
	}

	public void setAPhoto(String aPhoto) {
		set("aPhoto", aPhoto);
	}

	public String getAPhoto() {
		return get("aPhoto");
	}

	public void setACreateTime(java.util.Date aCreateTime) {
		set("aCreateTime", aCreateTime);
	}

	public java.util.Date getACreateTime() {
		return get("aCreateTime");
	}

	public void setAModifyTime(java.util.Date aModifyTime) {
		set("aModifyTime", aModifyTime);
	}

	public java.util.Date getAModifyTime() {
		return get("aModifyTime");
	}

}
