package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStopdeal<M extends BaseStopdeal<M>> extends Model<M> implements IBean {

	public void setSdId(java.math.BigInteger sdId) {
		set("sdId", sdId);
	}

	public java.math.BigInteger getSdId() {
		return get("sdId");
	}

	public void setSdUser(java.math.BigInteger sdUser) {
		set("sdUser", sdUser);
	}

	public java.math.BigInteger getSdUser() {
		return get("sdUser");
	}

	public void setSdStore(java.math.BigInteger sdStore) {
		set("sdStore", sdStore);
	}

	public java.math.BigInteger getSdStore() {
		return get("sdStore");
	}

	public void setSdProblem(String sdProblem) {
		set("sdProblem", sdProblem);
	}

	public String getSdProblem() {
		return get("sdProblem");
	}

	public void setSdPhoto(String sdPhoto) {
		set("sdPhoto", sdPhoto);
	}

	public String getSdPhoto() {
		return get("sdPhoto");
	}

	public void setSdApplyName(String sdApplyName) {
		set("sdApplyName", sdApplyName);
	}

	public String getSdApplyName() {
		return get("sdApplyName");
	}

	public void setSdApplyNum(String sdApplyNum) {
		set("sdApplyNum", sdApplyNum);
	}

	public String getSdApplyNum() {
		return get("sdApplyNum");
	}

	public void setSdApplyPhone(String sdApplyPhone) {
		set("sdApplyPhone", sdApplyPhone);
	}

	public String getSdApplyPhone() {
		return get("sdApplyPhone");
	}

	public void setSdFormId(String sdFormId) {
		set("sdFormId", sdFormId);
	}

	public String getSdFormId() {
		return get("sdFormId");
	}

	public void setSdCreateTime(java.util.Date sdCreateTime) {
		set("sdCreateTime", sdCreateTime);
	}

	public java.util.Date getSdCreateTime() {
		return get("sdCreateTime");
	}

	public void setSdModifyTime(java.util.Date sdModifyTime) {
		set("sdModifyTime", sdModifyTime);
	}

	public java.util.Date getSdModifyTime() {
		return get("sdModifyTime");
	}

}
