package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDevicebusiness<M extends BaseDevicebusiness<M>> extends Model<M> implements IBean {

	public void setDbId(java.math.BigInteger dbId) {
		set("dbId", dbId);
	}

	public java.math.BigInteger getDbId() {
		return get("dbId");
	}

	public void setDbImg(String dbImg) {
		set("dbImg", dbImg);
	}

	public String getDbImg() {
		return get("dbImg");
	}

	public void setDbDcpt(String dbDcpt) {
		set("dbDcpt", dbDcpt);
	}

	public String getDbDcpt() {
		return get("dbDcpt");
	}

	public void setDbOtherConnect(String dbOtherConnect) {
		set("dbOtherConnect", dbOtherConnect);
	}

	public String getDbOtherConnect() {
		return get("dbOtherConnect");
	}

	public void setDbUser(java.math.BigInteger dbUser) {
		set("dbUser", dbUser);
	}

	public java.math.BigInteger getDbUser() {
		return get("dbUser");
	}

	public void setDbType(Integer dbType) {
		set("dbType", dbType);
	}

	public Integer getDbType() {
		return get("dbType");
	}

	public void setDbLoc(String dbLoc) {
		set("dbLoc", dbLoc);
	}

	public String getDbLoc() {
		return get("dbLoc");
	}

	public void setDbLng(String dbLng) {
		set("dbLng", dbLng);
	}

	public String getDbLng() {
		return get("dbLng");
	}

	public void setDbLat(String dbLat) {
		set("dbLat", dbLat);
	}

	public String getDbLat() {
		return get("dbLat");
	}

	public void setDbOtherType(int dbOtherType) {
		set("dbOtherType", dbOtherType);
	}

	public int getDbOtherType() {
		return get("dbOtherType");
	}

	public void setDbName(String dbName) {
		set("dbName", dbName);
	}

	public String getDbName() {
		return get("dbName");
	}

	public void setDbPhone(String dbPhone) {
		set("dbPhone", dbPhone);
	}

	public String getDbPhone() {
		return get("dbPhone");
	}

	public void setDbDeviceType(String dbDeviceType) {
		set("dbDeviceType", dbDeviceType);
	}

	public String getDbDeviceType() {
		return get("dbDeviceType");
	}

	public void setDbExplain(String dbExplain) {
		set("dbExplain", dbExplain);
	}

	public String getDbExplain() {
		return get("dbExplain");
	}

	public void setDbStatus(Integer dbStatus) {
		set("dbStatus", dbStatus);
	}

	public Integer getDbStatus() {
		return get("dbStatus");
	}

	public void setDbFailReason(String dbFailReason) {
		set("dbFailReason", dbFailReason);
	}

	public String getDbFailReason() {
		return get("dbFailReason");
	}

	public void setDbCreateTime(java.util.Date dbCreateTime) {
		set("dbCreateTime", dbCreateTime);
	}

	public java.util.Date getDbCreateTime() {
		return get("dbCreateTime");
	}

	public void setDbModifyTime(java.util.Date dbModifyTime) {
		set("dbModifyTime", dbModifyTime);
	}

	public java.util.Date getDbModifyTime() {
		return get("dbModifyTime");
	}

}
