package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

import java.math.BigInteger;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePhoto<M extends BasePhoto<M>> extends Model<M> implements IBean {

	public void setPId(java.math.BigInteger pId) {
		set("pId", pId);
	}

	public java.math.BigInteger getPId() {
		return get("pId");
	}

	public void setPUrl(String pUrl) {
        set("pUrl", pUrl);
    }

    public String getPUrl() {
        return get("pUrl");
    }

    public void setPToId(String pToId) {
        set("pToId", pToId);
    }

    public String getPToId() {
        return get("pToId");
    }

    public void setPType(Integer pType) {
        set("pType", pType);
    }

    public Integer getPType() {
        return get("pType");
    }

    public void setPStatus(Integer pStatus) {
        set("pStatus", pStatus);
    }

    public Integer getPStatus() {
        return get("pStatus");
    }

	public void setPCreateTime(java.util.Date pCreateTime) {
		set("pCreateTime", pCreateTime);
	}

	public java.util.Date getPCreateTime() {
		return get("pCreateTime");
	}

	public void setPModifyTime(java.util.Date pModifyTime) {
		set("pModifyTime", pModifyTime);
	}

	public java.util.Date getPModifyTime() {
		return get("pModifyTime");
	}

}
