package com.shiyi.meng.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import sun.security.pkcs11.P11Util;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReportdevice<M extends BaseReportdevice<M>> extends Model<M> implements IBean {

    public void setRdId(java.math.BigInteger rdId) {
        set("rdId", rdId);
    }

    public java.math.BigInteger getRdId() {
        return get("rdId");
    }

    public void setRdReporter(java.math.BigInteger rdReporter) {
        set("rdReporter", rdReporter);
    }

    public java.math.BigInteger getRdReporter() {
        return get("rdReporter");
    }

    public void setRdDevice(java.math.BigInteger rdDevice) {
        set("rdDevice", rdDevice);
    }

    public java.math.BigInteger getRdDevice() {
        return get("rdDevice");
    }

    public void setRdOption(int rdOption) {
        set("rdOption", rdOption);
    }

    public int getRdOption() {
        return get("rdOption");
    }

    public void setRdDcpt(String rdDcpt) {
        set("rdDcpt", rdDcpt);
    }

    public String getRdDcpt() {
        return get("rdDcpt");
    }

    public void setRdImg(String rdImg) {
        set("rdImg", rdImg);
    }

    public String getRdImg() {
        return get("rdImg");
    }

    public void setRdName(String rdName) {
        set("rdName", rdName);
    }

    public String getRdName() {
        return get("rdName");
    }

    public void setRdPhone(String rdPhone) {
        set("rdPhone", rdPhone);
    }

    public String getRdPhone() {
        return get("rdPhone");
    }

    public void setRdOtherConnet(String rdOtherConnet) {
        set("rdOtherConnet", rdOtherConnet);
    }

    public String getRdOtherConnet() {
        return get("rdOtherConnet");
    }

    public void setRdStatus(Integer rdStatus) {
        set("rdStatus", rdStatus);
    }

    public Integer getRdStatus() {
        return get("rdStatus");
    }

    public void setRdFormId(String rdFormId) {
        set("rdFormId", rdFormId);
    }

    public String getRdFormId() {
        return get("rdFormId");
    }

    public void setRdCreateTime(java.util.Date rdCreateTime) {
        set("rdCreateTime", rdCreateTime);
    }

    public java.util.Date getRdCreateTime() {
        return get("rdCreateTime");
    }

    public void setRdModifyTime(java.util.Date rdModifyTime) {
        set("rdModifyTime", rdModifyTime);
    }

    public java.util.Date getRdModifyTime() {
        return get("rdModifyTime");
    }

}
