package com.shiyi.meng.model;

import com.shiyi.meng.model.base.BaseAccesscode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")

public class Accesscode extends BaseAccesscode<Accesscode> {
	public static final Accesscode dao = new Accesscode().dao();
}
