package com.shiyi.meng.model;

import com.shiyi.meng.model.base.BaseAdmin;
import org.springframework.context.annotation.Bean;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")

public class Admin extends BaseAdmin<Admin> {
	public static final Admin dao = new Admin().dao();
}
