package com.shiyi.meng.model;


import com.shiyi.meng.model.base.BaseAdvert;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Advert extends BaseAdvert<Advert> {
	public static final Advert dao = new Advert().dao();
}
