package com.shiyi.meng.model;


import com.shiyi.meng.model.base.BaseCityloc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cityloc extends BaseCityloc<Cityloc> {
	public static final Cityloc dao = new Cityloc().dao();
}
