package com.shiyi.meng.model;


import com.shiyi.meng.model.base.BaseContracttemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contracttemplate extends BaseContracttemplate<Contracttemplate> {
	public static final Contracttemplate dao = new Contracttemplate().dao();
}
