package com.shiyi.meng.model;


import com.shiyi.meng.model.base.BaseDevicetype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Devicetype extends BaseDevicetype<Devicetype> {
	public static final Devicetype dao = new Devicetype().dao();
}
