package com.shiyi.meng.model;


import com.shiyi.meng.model.base.BaseDevicebusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Devicebusiness extends BaseDevicebusiness<Devicebusiness> {
	public static final Devicebusiness dao = new Devicebusiness().dao();
}
