package com.shiyi.meng.model;

import com.shiyi.meng.model.base.BaseFindstore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Findstore extends BaseFindstore<Findstore> {
	public static final Findstore dao = new Findstore().dao();
}
