package com.shiyi.meng.model;


import com.shiyi.meng.model.base.BaseFollowstore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Followstore extends BaseFollowstore<Followstore> {
	public static final Followstore dao = new Followstore().dao();
}
