package com.shiyi.meng.model;


import com.shiyi.meng.model.base.BaseFollowdevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Followdevice extends BaseFollowdevice<Followdevice> {
	public static final Followdevice dao = new Followdevice().dao();
}
