package com.shiyi.meng.model;


import com.shiyi.meng.model.base.BasePhoto;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Photo extends BasePhoto<Photo> {
	public static final Photo dao = new Photo().dao();
}
