package com.shiyi.meng.model;


import com.shiyi.meng.model.base.BasePlatbill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Platbill extends BasePlatbill<Platbill> {
	public static final Platbill dao = new Platbill().dao();
}
