package com.shiyi.meng.model;

import com.shiyi.meng.model.base.BaseReportdevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reportdevice extends BaseReportdevice<Reportdevice> {
    public static final Reportdevice dao = new Reportdevice().dao();
}
