package com.shiyi.meng.model;

import com.shiyi.meng.model.base.BaseSignstore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Signstore extends BaseSignstore<Signstore> {
	public static final Signstore dao = new Signstore().dao();
}
