package com.shiyi.meng.model;

import com.shiyi.meng.model.base.BaseSmscode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Smscode extends BaseSmscode<Smscode> {
    public static final Smscode dao = new Smscode().dao();
}
