package com.shiyi.meng.model;

import com.shiyi.meng.model.base.BaseStopdeal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stopdeal extends BaseStopdeal<Stopdeal> {
	public static final Stopdeal dao = new Stopdeal().dao();
}
