package com.shiyi.meng.model;

import com.shiyi.meng.model.base.BaseStoreloc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Storeloc extends BaseStoreloc<Storeloc> {
	public static final Storeloc dao = new Storeloc().dao();
}
