package com.shiyi.meng.model;

import com.shiyi.meng.model.base.BaseTransfermoney;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Transfermoney extends BaseTransfermoney<Transfermoney> {
	public static final Transfermoney dao = new Transfermoney().dao();
}
